# -*- coding: utf-8 -*-
"""Modul_6_Integral_Metode_Scipy_Soal1_Syafrudin_Fahrul_Anas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iig2ORQS0zaE_RbVTC_3mnlYb50AOohK
"""

import numpy as np
from scipy import integrate
import matplotlib.pyplot as plotlib

# Define parameters
x_start = 0  # Memulai interval
x_stop = np.pi  # Akhir dari interval
x_steps_interval = 0.01  # Step size

# Mendefinisikan Array data
x_values = np.arange(x_start, x_stop, x_steps_interval)
y_values = x_values**2 * np.cos(x_values) + 3 * np.sin(2 * x_values)

# Plot fungsi kurva
plotlib.plot(x_values, y_values)

# Definisi lambda fungsi integral
integration_function = lambda x: x**2 * np.cos(x) + 3 * np.sin(2 * x)

# Hitung integral
integral, _ = integrate.quad(integration_function, x_start, x_stop)

# Cetak hasil integral
print("Hasil integral:")
print(integral)

# Tampilkan plotnya
plotlib.xlabel('x')
plotlib.ylabel('f(x)')
plotlib.title('Plot dari f(x) = x^2 cos(x) + 3sin(2x)')
plotlib.show()