# -*- coding: utf-8 -*-
"""Modul_6_Integral_Metode_Scipy_Contoh_Syafrudin_Fahrul_Anas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLWTt_O7lQ1PSVANbmsbeswMPWrftB53
"""

import numpy as np
from scipy import integrate
import matplotlib.pyplot as plotlib

#Define parameters
x_start =0 # Memulai interval
x_stop = 1 # akhir dari interval
x_steps_interval = 0.01 # Step size

# Mendefinisia Array data
x_values = np.arange(x_start, x_stop, x_steps_interval)
y_values = 2 * x_values * np.exp(np.sin(x_values)) + np.cos(np.exp(x_values))

#plot fungsi kurva
plotlib.plot(x_values, y_values)

#Definisi lambda fungsi integral
integration_function = lambda x: 2 * x * np.exp(np.sin(x)) + np.cos(np.exp(x))

# hitung integral (meniadakan eror)
integral, _ = integrate.quad(integration_function, x_start, x_stop)

# Cetak hasil integral
print("Hasil integral:")
print(integral)

# Tampilkan plotnya
plotlib.xlabel('x')
plotlib.ylabel('f(x)')
plotlib.title('Plot dari f(x) = 2x * e^(sin(x)) + cos(e^x)')
plotlib.show()